# Generated by Django 4.2.17 on 2025-03-14 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_ticket_status'),
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ticket'),
        ),
    ]
