# Generated by Django 5.1.4 on 2025-01-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCol', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=11)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('pix', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('enderecoCol', models.TextField()),
            ],
        ),
    ]
