# Generated by Django 5.1.4 on 2025-01-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_colaborador_usuario_alter_colaborador_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='banco',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nomesocialCol',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
