# Generated by Django 5.1.4 on 2025-01-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0003_colaborador_banco_colaborador_nomesocialcol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cpf_cnpj',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
