# Generated by Django 5.1.4 on 2025-01-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_cliente_alter_ticket_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('L', 'Levantamento'), ('O', 'Orçamento'), ('A', 'Aprovado'), ('F', 'Finalizado'), ('E', 'Emergencial')], max_length=1),
        ),
    ]
