# Generated by Django 4.2.17 on 2025-01-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_emergencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('L', 'Levantamento'), ('O', 'Orçamento'), ('A', 'Aprovado'), ('V', 'Vistoriado'), ('F', 'Finalizado')], default='L', max_length=1),
        ),
    ]
