# Generated by Django 4.2.17 on 2025-03-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('L', 'Levantamento'), ('O', 'Orçamento'), ('A', 'Aprovado'), ('V', 'Vistoriado'), ('F', 'Finalizado'), ('R', 'Rejeitado')], default='L', max_length=1),
        ),
    ]
